Set-Alias -Name 'Desktop' -Value 'Set-LocationDesktop'
Set-Alias -Name 'Downloads' -Value 'Set-LocationDownloads'
Set-Alias -Name 'Documents' -Value 'Set-LocationDocuments'
Set-Alias -Name 'Pictures' -Value 'Set-LocationPictures'
Set-Alias -Name 'Music' -Value 'Set-LocationMusic'
Set-Alias -Name 'Videos' -Value 'Set-LocationVideos'
Set-Alias -Name 'DevDrive' -Value 'Set-LocationDevDrive'
